# Generated by Django 4.0.5 on 2023-03-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('ServiceName', models.CharField(max_length=30)),
                ('description1', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
