# Generated by Django 4.0.5 on 2023-03-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_cleaning_description2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning',
            name='image',
            field=models.ImageField(upload_to='Services/images'),
        ),
    ]
