# Generated by Django 4.1.2 on 2023-03-24 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_carpenter_electics_plumbing_alter_cleaning_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=30)),
                ('comment', models.TextField()),
                ('rating', models.IntegerField(default=1)),
                ('dt', models.DateField(default=datetime.date(2023, 3, 24))),
            ],
        ),
    ]
