# Generated by Django 4.1.2 on 2023-03-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='password',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
