# Generated by Django 4.1.2 on 2023-03-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_userdetails_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='address1',
            field=models.CharField(default='Ahmedabad', max_length=50),
        ),
    ]
