# Generated by Django 4.1.2 on 2023-03-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_userdetails_address1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
