# Generated by Django 4.1.2 on 2023-03-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_alter_userdetails_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empdetails',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('work', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=25)),
                ('dob', models.DateTimeField(verbose_name='DateofBirth')),
            ],
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='address1',
            new_name='zipn',
        ),
    ]
