# Generated by Django 4.1.2 on 2023-03-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_empdetails_rename_address1_userdetails_zipn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='zipn',
            new_name='city',
        ),
        migrations.AlterField(
            model_name='empdetails',
            name='dob',
            field=models.DateField(),
        ),
    ]
