# Generated by Django 4.1.2 on 2023-03-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_rename_zipn_userdetails_city_alter_empdetails_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
