# Generated by Django 4.1.2 on 2023-03-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sigup',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
