# Generated by Django 4.0.5 on 2023-04-01 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
