# Generated by Django 4.0.5 on 2023-04-02 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0013_remove_cart_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
