# Generated by Django 4.0.5 on 2023-04-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0015_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='category',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='sno',
            field=models.CharField(max_length=50),
        ),
    ]
