# Generated by Django 4.0.5 on 2023-04-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0016_bookings_address_bookings_name_bookings_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='booking_status',
            field=models.BooleanField(default=False),
        ),
    ]
