# Generated by Django 4.0.5 on 2023-04-06 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0017_bookings_booking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='booking_status',
            new_name='complete_status',
        ),
    ]
