# Generated by Django 4.0.5 on 2023-04-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0018_rename_booking_status_bookings_complete_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='cancel_booking',
            field=models.BooleanField(default=False),
        ),
    ]
