# Generated by Django 4.2 on 2023-04-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0020_delete_login_empdetails_is_emp_empdetails_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetails',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
