# Generated by Django 4.2 on 2023-04-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0021_alter_empdetails_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetails',
            name='fname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
