# Generated by Django 4.2 on 2023-04-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0022_alter_empdetails_fname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetails',
            name='username',
            field=models.CharField(default='Emp_', max_length=30),
        ),
    ]
