# Generated by Django 4.2 on 2023-04-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0026_alter_empdetails_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetails',
            name='username',
            field=models.CharField(default='EMP_', max_length=30),
        ),
    ]
