# Generated by Django 4.0.5 on 2023-04-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0028_alter_bookings_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
