# Generated by Django 4.1.2 on 2023-03-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactMe',
            fields=[
                ('cno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=100)),
                ('condate', models.DateTimeField()),
            ],
        ),
    ]
