# Generated by Django 4.1.2 on 2023-03-18 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactme',
            name='condate',
        ),
    ]
