# Generated by Django 4.1.2 on 2023-03-19 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_remove_contactme_condate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactme',
            old_name='name',
            new_name='uname',
        ),
    ]
